### ISSUE TITLE
High level - Continue to refine current Chevron functions

### ISSUE THREAD

**Issue by crazycatandy** [insightsengineering/chevron#284]
- [x] insightsengineering/chevron-tasks#53 
- [x] insightsengineering/chevron-tasks#45 
- [x] insightsengineering/chevron-tasks#46 
- [x] insightsengineering/chevron-tasks#44 
- [x] insightsengineering/chevron-tasks#43
