### ISSUE TITLE
High Level - Continue to add more templates

### ISSUE THREAD

**Issue by crazycatandy** [insightsengineering/chevron#336]
- [x] insightsengineering/chevron-tasks#51 
- [x]  insightsengineering/chevron-tasks#50 
- [x] insightsengineering/chevron-tasks#39 
- [x]  insightsengineering/chevron-tasks#38 
- [ ]  insightsengineering/chevron#248 
- [x]  insightsengineering/chevron-tasks#36 
- [ ]  insightsengineering/chevron-tasks#56
